---
name: lint

on:
  push:
    branches: [master, main]
    # only when python files are changed
    paths: 
      - '**.py'
  pull_request:
    branches: [master, main]
  
  workflow_dispatch:

# set the run-name 
run-name: ${{ github.ref_name }} -> lint (
  ${{ github.run_attempt }}
  )


jobs:
  lint:

    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Echo current date and time
        id: datetime
        run: |
          echo "datetime: $(date '+%Y-%m-%d %H:%M:%S')"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install black
          pip install ruff
          pip install mypy
      
      - name: Lint with black
        run: |
          black --check src
      # ignore E501 (line too long)
      # Ignore I001 Import block is un-sorted or un-formatted
      # Ignore B008 function call in argument defaults
      - name: Lint with ruff
        run: |
          ruff check src --ignore=E501,I001,B008

      - name: Lint with mypy
        run: |
          mypy src --ignore-missing-imports
  