---
name: lint

on:
  push:
    branches: [master, main]
    # only when python files are changed
    paths: 
      - '**.py'
  pull_request:
    branches: [master, main]
  
  workflow_dispatch:

# set the run-name 
run-name: ${{ github.ref_name }} -> lint (
  ${{ github.run_attempt }}
  )


jobs:
  lint:

    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Echo current date and time
        id: datetime
        run: |
          echo "datetime: $(date '+%Y-%m-%d %H:%M:%S')"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Update pip and install hatch
        run: |
          export PIP_ROOT_USER_ACTION=ignore
          pip install --upgrade pip
          pip install hatch
  
      - name: Hatch lint all
        run: hatch run lint:all
