---
name: Test

on:
  push:
    branches: [master, main]
    # only when python files are changed
    paths: 
      - '**.py'
  pull_request:
    branches: [master, main]
  
  workflow_dispatch:

# set the run-name 
run-name: ${{ github.ref_name }} -> Test (
  ${{ github.run_attempt }}
  )


jobs:
  lint:

    name: Runs unit tests
    runs-on: ubuntu-latest

    steps:

      - name: Echo current date and time
        id: datetime
        run: |
          echo "datetime: $(date '+%Y-%m-%d %H:%M:%S')"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest
      
      - name: Run tests
        run: |
          pytest --log-level DEBUG tests